/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.test {
	import laya.ui.*;
	import laya.display.*;
	import script/GameUI.ts;

	public class TestSceneUI extends Scene {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":640,"runtime":"script/GameUI.ts","positionVariance_0":100,"maxPartices":100,"height":1136},"compId":1,"child":[{"type":"Button","props":{"width":200,"top":200,"skin":"comp/button.png","labelSize":20,"label":"按钮","height":60,"centerX":0},"compId":20}],"loadList":["comp/button.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}